# Generated by Django 6.1 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('diametro', models.FloatField()),
                ('costo_por_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_minimo', models.FloatField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
