# Generated by Django 6.1 on 2026-08-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], max_length=10)),
                ('subtipo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['tipo', 'subtipo'],
                'unique_together': {('tipo', 'subtipo')},
            },
        ),
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('diametro', models.FloatField()),
                ('costo_por_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso_inicial', models.FloatField()),
                ('peso_actual', models.FloatField()),
                ('estado', models.CharField(choices=[('Sellada', 'Sellada'), ('Abierta', 'Abierta'), ('Vacía', 'Vacía')], max_length=30)),
                ('fecha_compra', models.DateField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
            ],
            options={
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.FloatField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
            options={
                'unique_together': {('material', 'color')},
            },
        ),
    ]
