# Generated by Django 5.2.16 on 2026-09-01 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Operativa', 'Operativa'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], max_length=30)),
                ('horas_uso', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], max_length=10)),
                ('subtipo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['tipo', 'subtipo'],
                'unique_together': {('tipo', 'subtipo')},
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('notas', models.TextField(blank=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.printer')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('diametro', models.FloatField()),
                ('costo_por_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso_inicial', models.FloatField()),
                ('peso_actual', models.FloatField()),
                ('estado', models.CharField(choices=[('Sellada', 'Sellada'), ('Abierta', 'Abierta'), ('Vacía', 'Vacía')], max_length=30)),
                ('fecha_compra', models.DateField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
            ],
            options={
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_usados', models.FloatField()),
                ('print_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.printorder')),
                ('spool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spool')),
            ],
        ),
        migrations.AddField(
            model_name='printorder',
            name='spools',
            field=models.ManyToManyField(through='inventory.PrintOrderItem', to='inventory.spool'),
        ),
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.FloatField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
        ),
        migrations.AddConstraint(
            model_name='printorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('gramos_usados__gt', 0)), name='printorderitem_gramos_positivos'),
        ),
        migrations.AlterUniqueTogether(
            name='stockthreshold',
            unique_together={('material', 'color')},
        ),
    ]
