# Generated by Django 6.1 on 2026-08-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Operativa', 'Operativa'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], max_length=30)),
                ('horas_uso', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=100)),
                ('gramos_usados', models.FloatField()),
                ('duracion_minutos', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('notas', models.TextField(blank=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.printer')),
                ('spool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spool')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
